### ISSUE TITLE
Drones do not leave the depot

### ISSUE THREAD

**Issue by eugenikus8** [AivanF/factorio-Mining-Drones-Remastered#1]
Drones do not leave the depot after a power outage and its resumption

**Comment by kaiwerther** [comment]
noticed this too with solar - at a certain point drones no longer leave the depot.

**Comment by AivanF** [comment]
Hi, thanks for the report! I knew I missed some case to test while tried to make a smooth number of drones coming out during power shortage. Fixed the problem with v2.0.6, it's already published. Let me know if everything works fine or not now!

**Comment by eugenikus8** [comment]
Everything works. 
1. Is it possible to raise the size of the drone stack to 100?
2. There are 2 versions of the electric motor in AAI-Industry, blue and green. Is it possible to use a blue motor for the creation of drones, for which lubricant is not needed?

**Comment by AivanF** [comment]
@eugenikus8 
1. `Is it possible to raise the size of the drone stack to 100?`
  Absolutely possible! Let me add a startup setting for this.
2. `There are 2 versions of the electric motor in AAI-Industry, blue and green`
  I also had such idea, I'll add it too with one of the next releases.

**Comment by eugenikus8** [comment]
Where can I see the percentage of drone productivity (as for electric drills)?

**Comment by AivanF** [comment]
There is no such display for now. It's an interesting question where to show this info except considering your productivity research level. I will try to research if this is possible to add in depot's entity info.

**Comment by AivanF** [comment]
I'm closing the issue. If you have any other questions or suggestions, feel free to write in [mod's Discussions](https://mods.factorio.com/mod/Mining_Drones_Remastered/discussion) or [in Discord on my mods](https://discord.com/invite/7QCXn35mU5).
