### ISSUE TITLE
[2.0.7] attempt to index field 'af-mining-drones-se-allow' (a nil value)

### ISSUE THREAD

**Issue by Nipahu** [AivanF/factorio-Mining-Drones-Remastered#3]
I just updated to 2.0.7 with Space Exploration activated and I'm getting this error message at the start of the game:

![grafik](https://github.com/AivanF/factorio-Mining-Drones-Remastered/assets/44159192/8eab4961-79fe-4888-b6a7-82760c34cb51)

**Comment by mbbhudgins** [comment]
I am also having this issue.
SE, K2, and 248K are the major overhaul mods installed.

**Comment by AivanF** [comment]
Thanks for the report, I just fixed the error in v2.0.8, try it.

**Comment by Nipahu** [comment]
The error is gone and I can start the game with 2.0.9. Thank you.
