### ISSUE TITLE
Ukrainian translation in ru locale

### ISSUE THREAD

**Issue by eugenikus8** [AivanF/factorio-Mining-Drones-Remastered#5]
Here is the correct translation ru locale

af-mining-drones-aai-elengine=Большой электромотор
af-mining-drones-aai-elmotor=Малый электромотор
af-mining-drones-aai-engine=Многоцилиндровый двигатель
af-mining-drones-aai-motor=Одноцилиндровый двигатель

**Comment by AivanF** [comment]
Yes, I accidentally swapped Ru and Uk texts for these settings. Fixed it, will be published with the next release.

Btw, I manage texts with [a Google Sheets table](https://docs.google.com/spreadsheets/d/11H5p7jTiUQckTrTv250iNWP41sX4aKNjZMAzm3t_UcI) and [a Python script](https://github.com/AivanF/factorio-Mining-Drones-Remastered/blob/main/scripts/locales.py) to speed up the process getting rid of manual CFG files editing.
