### ISSUE TITLE
Russian translation in uk locale

### ISSUE THREAD

**Issue by eugenikus8** [AivanF/factorio-Mining-Drones-Remastered#6]
Here is the correct translation ukrainian locale

af-mining-drones-aai-elengine=Великий електродвигун
af-mining-drones-aai-elmotor=Маленький електродвигун
af-mining-drones-aai-engine=Багатоциліндровий двигун
af-mining-drones-aai-motor=Одноциліндровый двигун

**Comment by AivanF** [comment]
No need of spanning similar issues 🙃
