### ISSUE TITLE
Krastorio2

### ISSUE THREAD

**Issue by eugenikus8** [AivanF/factorio-Mining-Drones-Remastered#7]
Krastorio2 . When choosing a green chip for crafting drones, an automation core is used instead of a chip
https://imgur.com/a/tXGrbL6
https://imgur.com/a/28AKBR5

**Comment by AivanF** [comment]
Well, this means Krastorio2 replaced vanillas green chip with "automation core" using the same internal entity name `electronic-circuit`.

AAI Industry mod does similar changes replacing vanillas burner/electric engines with small and big versions. I added special recipe settings to support all the options for this mod (which are presented on your screenshot). Seems like Krastorio2 requires similar changes.

I never tried this mod, so I need more info to add better support for it. Are there green chips in Krastorio2? If yes, what's there new internal name? If no, what other ingredient can be used instead? I can try this mod and research myself, but if you can answer to these questions, it will speed up the process!

**Comment by eugenikus8** [comment]
https://imgur.com/a/11ggsVM

**Comment by AivanF** [comment]
That's weird! Seems like Krastorio2 automatically changes recipes replacing green chips with this automation core 🤔 I'll try this mod to research how to fix this, when I'll have some free time.
